spring.application.name=java
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/sece
spring.datasource.username=root
spring.datasource.password=yazhu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true